name: Update TCG Database

on:
  schedule:
    - cron: '0 10 * * *'   # runs every day at 02:00 PST (adjust below if you want a different time)
  workflow_dispatch:     # allows manual runs from Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run update script
      run: python 3_Search_Process.py

    - name: Commit and push updated CSV (if changed)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add search_database.csv
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update search_database.csv"
          git push
        fi
